services:
  api-gateway:
    image: artorient/api-gateway:latest
    container_name: api_gateway
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET: ${JWT_SECRET}
      USER_SERVICE_URL: http://user-service:8080
      AUTH_SERVICE_URL: http://auth-service:8081
      ORDER_SERVICE_URL: http://order-service:8082
    depends_on:
      - auth-service
      - user-service
      - order-service

  auth-service:
    image: artorient/auth-service:latest
    container_name: auth_service_app
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      AUTH_DB_HOST: auth-postgres
      AUTH_DB_PORT: 5432
      AUTH_DB_NAME: ${AUTH_DB_NAME}
      AUTH_DB_USER: ${AUTH_DB_USER}
      AUTH_DB_PASSWORD: ${AUTH_DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - auth-postgres

  auth-postgres:
    image: postgres:15
    container_name: auth_service_postgres
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data

  user-service:
    image: artorient/user-service:latest
    container_name: user_service_app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: user-postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: user_service_redis
      REDIS_PORT: 6379
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - user-postgres
      - redis

  user-postgres:
    image: postgres:15
    container_name: user_service_postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - user_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: user_service_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  order-service:
    image: artorient/order-service:latest
    container_name: order_service_app
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      ORDER_DB_HOST: order-postgres
      ORDER_DB_PORT: 5432
      ORDER_DB_NAME: ${ORDER_DB_NAME}
      ORDER_DB_USERNAME: ${ORDER_DB_USERNAME}
      ORDER_DB_PASSWORD: ${ORDER_DB_PASSWORD}
      USER_SERVICE_URL: http://user-service:8080
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - order-postgres
      - user-service

  order-postgres:
    image: postgres:15
    container_name: order_service_postgres
    environment:
      POSTGRES_DB: ${ORDER_DB_NAME}
      POSTGRES_USER: ${ORDER_DB_USERNAME}
      POSTGRES_PASSWORD: ${ORDER_DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - order_postgres_data:/var/lib/postgresql/data

volumes:
  auth_postgres_data:
  user_postgres_data:
  order_postgres_data:
  redis_data: